name: RepoUpdater
on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    name: RepoUpdater
    runs-on: ubuntu-latest
    steps:
      - name: Update
        uses: igr/c19json/.github/actions/action@master
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      - name: Echo the time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
