name: RepoUpdater
on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    name: RepoUpdater
    runs-on: ubuntu-latest
    steps:
    - name: RepoUpdate
      uses: igr/c19json/.github/actions@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
